Fixed #2: adding minimal site informations.
Decysif/website pull request #3
Opened 2024-02-02 09:14 UTC by Ninjapouet

Here comes a more complete minimal site.

2024-02-02 17:59 UTC, claudemarche requested changes
Comment on peut visualiser le site ?

2024-02-02 17:59 UTC, claudemarche commented on content/_index.fr.md
> +DéCySif est un projet i-Demo régional de R&D regroupant Adacore, le CEA,
Ben non pas le CEA !

2024-02-08 12:59 UTC, Ninjapouet commented on content/_index.fr.md
> +DéCySif est un projet i-Demo régional de R&D regroupant Adacore, le CEA,
Non en effet ! C'est corrigé dans la dernière version.

2024-02-09 11:24 UTC, claudemarche approved these changes

2024-02-09 11:24 UTC, merged